server:
  url:      ws://ws.saso.dev/
  bind:
    host:   ~
    port:   7692

db:
  host:     saso.dev
  port:     ~
  database: app
  user:     vagrant
  password: vagrant

redis:
  host:     saso.dev
  port:     ~
  password: ~
