server:
  url:      ws://ws.saso.dev/
  bind:
    host:   ~
    port:   7692

db:
  host:     saso.dev
  port:     ~
  database: app
  user:     vagrant
  password: vagrant

redis:
  host:     saso.dev
  port:     ~
  password: ~

# False if templates in templates/ should be recompiled  on every request.
# Otherwise, the server must be restarted to update changes.
cache-templates: false

# How many concurrent connections may exist per user.
max-connections-per-user: 3
