debug: true

server:
  url:       ws://ws.saso.dev/
  bind:
    host:    127.0.0.1
    port:    7692

db:
  host:      saso.dev
  port:      5432
  database:  app
  user:      vagrant
  password:  vagrant

redis:
  host:      saso.dev
  port:      6379
  password:  ~

limits:
  connections_per_user: 3
